#!/usr/bin/env bash

#
#
# Andreas extention to px4_sim_script_extention_automated
# Seyfullah Seker
# Bachelorarbeit- Parameterstudie
#
# extension to 'px4_sim_script'
# 
#
#Please set values/strings: 
#launchname startvalue endvalue email; e.g.:
: <<KOMMENTARIO
./px4_sim_script_all_worlds city_obst
KOMMENTARIO

####### put this file and px4_sim_script in the main directory (/home/"your id") ############

###		POSSIBLE ERROR		### 
# when using script from GitKraken on Ubuntu either:  
#	- use dos2unix to change file format to Unix 
#	- copy-paste content to file created on Ubuntu directly rather than downloading it from GitKraken 

echo "Skript started"

launchname=${1?$(tput setaf 1)Error: no launchname or textfile given (eg. simple_obst or check_missing)$(tput setaf 7)}
device=${2?$(tput setaf 1)Error: give device type, cpu or gpu$(tput setaf 7)}


echo e
if [ $device != "cpu" ] && [ $device != "gpu" ];
then
  printf '%s\n' "ValueError: device must be either cpu or gpu, you typed $device" >&2  # write error message to stderr
  exit 1                                  # or exit $test_result
fi

	
	start=1054;
	echo $launchname
	if [[ $launchname == "simple_obst" ]]; then
		end=900
	elif [[ $launchname == "natural_obst" ]]; then
		end=165
	elif [[ $launchname == "city_obst" ]]; then
		end=1408
	else
		
		end=0
	fi
	
	if [[ $launchname == "all" ]]; then #[[ end==0 ]]; then
		for i in 1 2 3
		do
			case $i in
			  1) 
				end=900
				launchname="simple_obst";;
			  2) 
				end=165
				launchname="natural_obst";;
			  3) 
				end=1408
				launchname="city_obst";;
			esac
			goal_x=(default) 
			goal_y=(default) 
			goal_z=(default) 
			t=$start
			dir=$(eval echo ~$USER)
		 
			echo "start launch file"

			while (( $t <= $end )) 
			 do  
				launchfile=("HANNASSCAPES_$launchname"_"$t".launch); 
		 
				if [ ! -f "$dir"/DeepPX4/src/avoidance/local_planner/launch/HANNASSCAPES/"$launchfile" ]; then	### cheking if given launchfile exists/is in the correct directory ### 
				    tput setaf 1; echo "Error:launchfile not found!" ;tput setaf 7; 
				    echo "Enterd: $launchname "; 
				    printf "Searched launchfile: %s\n" "$launchfile" 
					exit 1  
				fi 
				 
				t=$(echo "($t+1)" | bc)
		 		./px4_sim_script_all_worlds_nodelet_HANNASSCAPES $launchfile $device;
				
				#conda activate paddleseg_cpu
				#cd ~/DeepPX4/src/scripts
				#python parameter_tuner.py

			done
		done
	else
		goal_x=(default) 
		goal_y=(default) 
		goal_z=(default) 
		t=$start 
		dir=$(eval echo ~$USER)
	 
		while (( $t <= $end )) 
		 do  
			launchfile=("HANNASSCAPES_$launchname"_"$t".launch); 
	 		



			if [ ! -f "$dir"/DeepPX4/src/avoidance/local_planner/launch/HANNASSCAPES/"$launchfile" ]; then	### cheking if given launchfile exists/is in the correct directory ### 
			    tput setaf 1; echo "Error:launchfile not found!" ;tput setaf 7; 
			    echo "Enterd: $launchname "; 
			    printf "Searched launchfile: %s\n" "$launchfile" 
				exit 1  
			fi 
			
			
			echo $t
			# just start specific worlds (e.g. incase they had ros connection errors )
	 		if [ $launchfile != "HANNASSCAPES_simple_obst_572.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_742.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_525.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_813.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_251.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_678.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_731.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_291.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_623.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_445.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_700.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_848.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_774.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_497.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_789.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_881.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_765.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_11.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_866.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_786.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_420.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_580.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_308.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_723.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_66.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_368.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_435.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_817.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_201.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_215.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_520.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_452.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_464.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_785.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_349.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_219.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_807.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_501.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_841.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_455.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_636.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_847.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_453.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_719.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_390.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_315.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_494.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_168.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_735.launch" ] && \
				[ $launchfile != "HANNASSCAPES_simple_obst_194.launch" ]

			then
				#t=$(echo "($t+1)" | bc)
				#continue
				echo " "
			fi
			t=$(echo "($t+1)" | bc)
	 		./px4_sim_script_all_worlds_nodelet_HANNASSCAPES $launchfile $device;
			wait < <(jobs -p)
			sleep 2
		done
	fi
