#!/usr/bin/env bash
#
#
# Adaption of px4_sim_script by Andreas Thoma
# Bachelorarbeit- Parameterstudie
#
# Durchführung einer Flugmission und Erfassung der Daten
# 
#


# Version 1.0 - new Pc

#checking if required tools are installed
if ! command -v xmlstarlet &> /dev/null;
then
    sudo apt-get install xmlstarlet 	### installing xmlstarlet ###
    exit
fi

echo "in nodelet"

#setting inputs to variables
launchfile=${1?$(tput setaf 1)Error: no launchfile given$(tput setaf 7)}
device=${2?$(tput setaf 1)Error: no device given$(tput setaf 7)}

#init
p=1
dir=$(eval echo ~$USER)
goal_x_takeoff=0
goal_y_takeoff=0
goal_z_takeoff=5
l=1


#creating resutls folder
save_path="$dir/bagfiles_all_worlds";
mkdir -p $save_path;	### creating bagifiles directory ###
mkdir -p "$dir/bagfiles_all_worlds/tlog";
mkdir -p "$dir/bagfiles_all_worlds/tlog/ros";
mkdir -p "$dir/bagfiles_all_worlds/tlog/seg";
mkdir -p "$dir/bagfiles_all_worlds/tlog/dynamic_rec";
mkdir -p "$dir/bagfiles_all_worlds/tlog/dynamic_rec2";


run=true;

while ($run)
do
	#Schleifen Init
	SECONDS=0

	#killing all previous ros nodes, etc.
	rosnode kill /my_bag 2> /dev/null ; ### 2> /dev/null suppresses Error messages ### 		
	killall -2 -w -q roslaunch;   	### -w wait for processes to die ; -q no complain if nothing closed ; -v signal if succesfull ; -g = processgroup ; ###  
	killall -w -q gzserver;		
		 
	#set goal variables
	goal_x=$(xmlstarlet sel -t -v "/launch/node//param[@name='goal_x_param']/@value" "$dir"/catkin_ws/src/avoidance/local_planner/launch/HANNASSCAPES/"$launchfile"); 
	goal_y=$(xmlstarlet sel -t -v "/launch/node//param[@name='goal_y_param']/@value" "$dir"/catkin_ws/src/avoidance/local_planner/launch/HANNASSCAPES/"$launchfile"); 
	goal_z=$(xmlstarlet sel -t -v "/launch/node//param[@name='goal_z_param']/@value" "$dir"/catkin_ws/src/avoidance/local_planner/launch/HANNASSCAPES/"$launchfile"); 
	goal=("$goal_x","$goal_y","$goal_z")
	echo $goal_z

	# Time Limits
	TIME_LIMIT=$(echo "(($goal_x*11000/50)*90)/10000+60" | bc )
	takeoff_time=60

	#set names
	name=("$launchfile"_"${goal[@]}"_"$l")
	name1=("$launchfile"_"${goal[@]}"_"$l".bag)
	name2=("$launchfile"_"${goal[@]}"_"$l"_error.bag)
			
	#start simulation
	echo "start local_planner"

	xterm -hold -e "roslaunch local_planner $launchfile >> '$save_path/tlog/ros/$name1.txt' 2>&1" &
	ros_pid="$!" # store process pid for later killing    
	sleep 10
	if    ### checking for errors at the beginning ###
	      ! pgrep -f "gazebo-" >/dev/null  	 	||
	      ! pgrep -f "mavros-" >/dev/null 		 	||
	      #! pgrep -f "gazebo_gui-" >/dev/null 	 	||
	      ! pgrep -f "local_planner_manager-" >/dev/null 	||
	      ! pgrep -f "local_planner_nodelet-" >/dev/null 	||
	      ! pgrep -f "rviz-" >/dev/null	; 
	then continue 
	else	### setting parameters; recording data; takeoff request; setting first waypoint to 5,0,0 to be able to use negative z-direction ###  					  
		############ for optimization #####
		 xterm -hold -e "rosrun dynamic_reconfigure dynparam set local_planner_nodelet goal_z_param '$goal_z_takeoff' >> '$save_path/tlog/dynamic_rec/$name1.txt' 2>&1;
						  timeout 5s rostopic pub -1 /move_base_simple/goal geometry_msgs/PoseStamped '{pose: {position: {x: '$goal_x_takeoff', y: '$goal_y_takeoff', z: '$goal_z_takeoff'}}}' >> '$save_path/tlog/dynamic_rec/$name1.txt' 2>&1;
						  rosrun dynamic_reconfigure dynparam set local_planner_nodelet goal_z_param '$goal_z_takeoff' >> '$save_path/tlog/dynamic_rec/$name1.txt' 2>&1;
						  rosrun mavros mavsys mode -c OFFBOARD;rosrun mavros mavsafety arm;cd ~/bagfiles_all_worlds >> '$save_path/tlog/dynamic_rec/$name1.txt' 2>&1; 
						  rosbag record -O '$save_path'/'${name[*]}'.bag /mavros/local_position /mavros/battery /mavros/home_position/home /mavros/local_position/accel /mavros/local_position/pose /mavros/local_position/velocity_body_cov /mavros/local_position/velocity_body /local_planner_nodelet/parameter_descriptions /local_planner_nodelet/parameter_updates /mavros/imu/data_raw /mavros/local_position/velocity_local /drone /path_actual __name:=my_bag  >> '$save_path/tlog/dynamic_rec/$name1.txt' 2>&1" &
		dynrec_pid="$!" # store process pid for later killing
		sleep 5;
		echo "parameter tuner terminal"
		xterm -hold -e "cd ~/DeepPX4; catkin_make >> '$save_path/tlog/seg/$name1.txt' 2>&1;
						source devel/setup.bash >> '$save_path/tlog/seg/$name1.txt' 2>&1;
						source ~/anaconda3/etc/profile.d/conda.sh >> '$save_path/tlog/seg/$name1.txt' 2>&1; 							conda activate paddleseg_$device >> '$save_path/tlog/seg/$name1.txt' 2>&1;
						cd ~/DeepPX4/src/parameter_tuning/scripts >> '$save_path/tlog/seg/$name1.txt' 2>&1; 
						python parameter_tuner.py --goal_z=$goal_z>> '$save_path/tlog/seg/$name1.txt' 2>&1" &
		seg_pid="$!" # store pid for later killing
		
		sleep 3			
	fi

	##############
	u=1; sleep 5;
	while [ "$SECONDS" -le "$takeoff_time" ] 	### checking if first waypoint (0,0,5) is reached and set new waypoint (our actual goal) ###
	do
	  sleep 0.1; 
	  if
	  ( (( $(echo "$(echo "$goal_x_takeoff - 1" | bc) < $(timeout 4s rostopic echo -p --nostr --noarr -n1 /mavros/local_position/pose | awk -F',' '{print $4}' |awk 'FNR == 2 {print}')"  | bc -l) )) &&     
	    (( $(echo "$(echo "$goal_y_takeoff - 1" | bc) < $(timeout 4s rostopic echo -p --nostr --noarr -n1 /mavros/local_position/pose | awk -F',' '{print $5}' |awk 'FNR == 2 {print}')"  | bc -l) )) &&	
	    (( $(echo "$(echo "$goal_z_takeoff - 4.5" | bc) < $(timeout 4s rostopic echo -p --nostr --noarr -n1 /mavros/local_position/pose | awk -F',' '{print $6}' |awk 'FNR == 2 {print}')"  | bc -l) )) &&
	    (( $(echo "$(echo "$goal_x_takeoff + 1" | bc) > $(timeout 4s rostopic echo -p --nostr --noarr -n1 /mavros/local_position/pose | awk -F',' '{print $4}' |awk 'FNR == 2 {print}')"  | bc -l) )) &&     
	    (( $(echo "$(echo "$goal_y_takeoff + 1" | bc) > $(timeout 4s rostopic echo -p --nostr --noarr -n1 /mavros/local_position/pose | awk -F',' '{print $5}' |awk 'FNR == 2 {print}')"  | bc -l) )) && 
	    (( $(echo "$(echo "$goal_z_takeoff + 1" | bc) > $(timeout 4s rostopic echo -p --nostr --noarr -n1 /mavros/local_position/pose | awk -F',' '{print $6}' |awk 'FNR == 2 {print}')"  | bc -l) )) ) ; 
	  then
		xterm -hold -e "rosrun dynamic_reconfigure dynparam set local_planner_nodelet goal_z_param '$goal_z'
		rostopic pub -l /move_base_simple/goal geometry_msgs/PoseStamped '{header: {frame_id: 'local_origin'}, pose: {position: {x: '$goal_x', y: '$goal_y', z: '$goal_z'}}}' >> '$save_path/tlog/dynamic_rec2/$name1.txt' 2>&1" &
 		dynrec_pid2="$!" # pid store for killing process late

		#'rosrun dynamic_reconfigure dynparam set local_planner_nodelet goal_z_param '$goal_z';';
# rostopic pub -l /goal_position visualization_msgs/MarkerArray '{header: {frame_id: 'local_origin'}, pose: {position: {x: '$goal_x', y: '$goal_y', z: '$goal_z'}}}'
		u=0;
		break
	  fi 
	done	 

 
	######################################################################################################################################
	if [ $u == 1 ] ; then 
		continue 	
	fi 

	################################	cheking if drone has made progress (is the drone flying back and forth in y-direction?)	############# 
	j1=0;
	j2=0; 
	amount_positiv_y_heading=0; 
	amount_negativ_y_heading=0;
	turnover=0;
	definiton_turn=2;
	reached_goal=0;
	echo "z koordinate soll: $goal_z";

	while [ "$SECONDS" -le "$TIME_LIMIT" ]   
	do     

		sleep 0.1; 
		if    ### checking for errors ###
		      ! pgrep -f "gazebo-" >/dev/null  	 	||
		      ! pgrep -f "mavros-" >/dev/null 		 	||
		      #! pgrep -f "gazebo_gui-9" >/dev/null 	 	||
		      ! pgrep -f "local_planner_manager-" >/dev/null 	||
		      ! pgrep -f "local_planner_nodelet-" >/dev/null 	||
		      ! pgrep -f "rviz-" >/dev/null		 ;
		then  
			continue 2
		elif 
	  ( (( $(echo "$(echo "$goal_x - 0.5" | bc) < $(timeout 4s rostopic echo -p --nostr --noarr -n1 /mavros/local_position/pose | awk -F',' '{print $4}' |awk 'FNR == 2 {print}')"  | bc -l) )) &&     
	    (( $(echo "$(echo "$goal_y - 0.5" | bc) < $(timeout 4s rostopic echo -p --nostr --noarr -n1 /mavros/local_position/pose | awk -F',' '{print $5}' |awk 'FNR == 2 {print}')"  | bc -l) )) &&	
	    (( $(echo "$(echo "$goal_z - 0.5" | bc) < $(timeout 4s rostopic echo -p --nostr --noarr -n1 /mavros/local_position/pose | awk -F',' '{print $6}' |awk 'FNR == 2 {print}')"  | bc -l) )) &&
	    (( $(echo "$(echo "$goal_x + 0.5" | bc) > $(timeout 4s rostopic echo -p --nostr --noarr -n1 /mavros/local_position/pose | awk -F',' '{print $4}' |awk 'FNR == 2 {print}')"  | bc -l) )) &&     
	    (( $(echo "$(echo "$goal_y + 0.5" | bc) > $(timeout 4s rostopic echo -p --nostr --noarr -n1 /mavros/local_position/pose | awk -F',' '{print $5}' |awk 'FNR == 2 {print}')"  | bc -l) )) && 
	    (( $(echo "$(echo "$goal_z + 0.5" | bc) > $(timeout 4s rostopic echo -p --nostr --noarr -n1 /mavros/local_position/pose | awk -F',' '{print $6}' |awk 'FNR == 2 {print}')"  | bc -l) )) ) ;
		then

			reached_goal=$(echo "($reached_goal+1)" | bc);
			if [ $reached_goal == 2 ] ;then 
				p=0;
				run=false;
				break
			fi

		else #Simulation läuft

			reached_goal=0;
			j1=$j2;	
			j2=$(timeout 4s rostopic echo -p --nostr --noarr -n1 /mavros/local_position/pose | awk -F',' '{print $5}' |awk 'FNR == 2 {print}')

			if (( $(echo "$j1 > $j2" | bc -l) ));then			#x
				amount_negativ_y_heading=$(echo "($amount_negativ_y_heading+1)" | bc);
			elif (( $(echo "$j1 < $j2" | bc -l) ));then			#x
				amount_positiv_y_heading=$(echo "($amount_positiv_y_heading+1)" | bc);					
			fi

			if [ $amount_positiv_y_heading -ge $definiton_turn ] && [ $amount_negativ_y_heading -ge $definiton_turn ] ;then  #(x)
				turnover=$(echo "($turnover+1)" | bc);
				if [ $turnover == 1 ] ;then		#x	
					reference_x_position=$(timeout 4s rostopic echo -p --nostr --noarr -n1 /mavros/local_position/pose | awk -F',' '{print $4}' |awk 'FNR == 2 {print}')
				elif [ $turnover == 3 ] ;then	#x
					if (( $(echo "$(echo "$reference_x_position + 2" | bc) > $(timeout 4s rostopic echo -p --nostr --noarr -n1 /mavros/local_position/pose | awk -F',' '{print $4}' |awk 'FNR == 2 {print}')"  | bc -l) ));then		
						run=false; break;
					else
						turnover=0;
					fi
				fi		
				amount_positiv_y_heading=0;
				amount_negativ_y_heading=0;					
			fi

		fi		
	done
#	if [ "$SECONDS" -gt "$TIME_LIMIT" ]; then 
#		run=false; break;
#	fi
	run=false;
done

#kill last node
kill -9 "$seg_pid"
rosnode kill /my_bag;		   		
killall -2 -w  roslaunch ;
killall -q gzserver
kill -9 "$ros_pid"
echo "killed gzserver about to kill all terminals"
#kill -- -$pid
#wmctrl -F -c segterminal
#kill gnome-terminal segterminal
echo "saving logfile"
#echo "killed gnome-terminal"
#check if last simulation was successfull
if [ $p == 1 ] && [ -f "$save_path/$name1" ]; then
mv "$save_path"/"$name1" "$save_path"/"$name2"
fi


#kill -9 "$dynrec_pid"
#kill -9 "$dynrec_pid2"
kill $(jobs -p)
wait < <(jobs -p)


