// Generated by gencpp from file segmentation/Segmentation.msg
// DO NOT EDIT!


#ifndef SEGMENTATION_MESSAGE_SEGMENTATION_H
#define SEGMENTATION_MESSAGE_SEGMENTATION_H

#include <ros/service_traits.h>


#include <segmentation/SegmentationRequest.h>
#include <segmentation/SegmentationResponse.h>


namespace segmentation
{

struct Segmentation
{

typedef SegmentationRequest Request;
typedef SegmentationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Segmentation
} // namespace segmentation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::segmentation::Segmentation > {
  static const char* value()
  {
    return "854247d4037fd8f89b2267c18c304a42";
  }

  static const char* value(const ::segmentation::Segmentation&) { return value(); }
};

template<>
struct DataType< ::segmentation::Segmentation > {
  static const char* value()
  {
    return "segmentation/Segmentation";
  }

  static const char* value(const ::segmentation::Segmentation&) { return value(); }
};


// service_traits::MD5Sum< ::segmentation::SegmentationRequest> should match
// service_traits::MD5Sum< ::segmentation::Segmentation >
template<>
struct MD5Sum< ::segmentation::SegmentationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::segmentation::Segmentation >::value();
  }
  static const char* value(const ::segmentation::SegmentationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::segmentation::SegmentationRequest> should match
// service_traits::DataType< ::segmentation::Segmentation >
template<>
struct DataType< ::segmentation::SegmentationRequest>
{
  static const char* value()
  {
    return DataType< ::segmentation::Segmentation >::value();
  }
  static const char* value(const ::segmentation::SegmentationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::segmentation::SegmentationResponse> should match
// service_traits::MD5Sum< ::segmentation::Segmentation >
template<>
struct MD5Sum< ::segmentation::SegmentationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::segmentation::Segmentation >::value();
  }
  static const char* value(const ::segmentation::SegmentationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::segmentation::SegmentationResponse> should match
// service_traits::DataType< ::segmentation::Segmentation >
template<>
struct DataType< ::segmentation::SegmentationResponse>
{
  static const char* value()
  {
    return DataType< ::segmentation::Segmentation >::value();
  }
  static const char* value(const ::segmentation::SegmentationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SEGMENTATION_MESSAGE_SEGMENTATION_H
